### ISSUE TITLE
Hanging Installation on Windows

### ISSUE THREAD

**Issue by simonphughes** [pencilblue/pencilblue#1024]
I am installing PencilBlue on WIndows, and have installed all the pre-requisites. However when I issue the command pbctrl install it gets most of the way through the installation but hangs at the stage where it is updating config.js

If I terminate the process at this point and issue pbctrl start the application starts up and I can get to the initial setup page where i am requested to create an admin user. If i fill in the details and submit I get an HTTP 500 error, and the message 
TypeError: post.hasOwnProperty is not a function
    at Function.DocumentCreatorModule.DocumentCreator.passwordHash (C:\Program Files\Git\dev\pencilblue\pencilblue\include\model\create_document.js:85:18)
    at Function.DocumentCreatorModule.DocumentCreator.create (C:\Program Files\Git\dev\pencilblue\pencilblue\include\model\create_document.js:51:25)
    at C:\Program Files\Git\dev\pencilblue\pencilblue\plugins\pencilblue\controllers\actions\setup.js:121:55
    at C:\Program Files\Git\dev\pencilblue\pencilblue\node_modules\async\lib\async.js:610:21
    at C:\Program Files\Git\dev\pencilblue\pencilblue\node_modules\async\lib\async.js:249:17
    at iterate (C:\Program Files\Git\dev\pencilblue\pencilblue\node_modules\async\lib\async.js:149:13)
    at async.eachSeries (C:\Program Files\Git\dev\pencilblue\pencilblue\node_modules\async\lib\async.js:165:9)
    at _asyncMap (C:\Program Files\Git\dev\pencilblue\pencilblue\node_modules\async\lib\async.js:248:13)
    at Object.mapSeries (C:\Program Files\Git\dev\pencilblue\pencilblue\node_modules\async\lib\async.js:231:23)
    at Object.async.series (C:\Program Files\Git\dev\pencilblue\pencilblue\node_modules\async\lib\async.js:608:19)

Help would be much appreciated.
Regards
Simon

**Comment by simonphughes** [comment]
Just in case anyone else has the same issues, i uninstalled Node 6, installed Node 4.4.3 and the installation is now working. It still hangs when updating the config.js file, however the application still works.

**Comment by brianhyder** [comment]
Not sure what the hanging is about for the config file.  We can look at that.  However, you can find the supported versions of node on our README and in the package.json
