### ISSUE TITLE
Error when launch in Node.js 6.0

### ISSUE THREAD

**Issue by JLKM** [pencilblue/pencilblue#1030]
My Windows/Node.js 5.7/PencilBlue-installation has worked fine for more than a month. But after upgrading to Node.js 6.0 last week the good times came to an end.

I get the login window for PencilBlue, which is version 0.5. But after entering correct username/password, I now get an error 500 with the following message;

credentials.hasOwnProperty is not a function

Have also seen:
post.hasOwnProperty is not a function

The error and message is accurately the same on my Linux/Node.js 6.0/PencilBlue-installation. So the error has to be connected to 6.0, not Linux or Windows.

Before trying to login I noticed the following new lines in the command prompt, when starting PencilBlue with pbctrl start:

(node:8744) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:8696) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

Should I downgrade to 5.7 (would really hate that), or is a fix for PencilBlue in sight?

StackTrace/Log:
500
credentials.hasOwnProperty is not a function
TypeError: credentials.hasOwnProperty is not a function
    at FormAuthentication.AuthenticationModule.UsernamePasswordAuthentication.authenticate (/share/CACHEDEV1_DATA/pbtest/include/security/authentication/index.js:65:25)
    at FormAuthentication.AuthenticationModule.FormAuthentication.authenticate (/share/CACHEDEV1_DATA/pbtest/include/security/authentication/index.js:97:58)
    at doAuthentication (/share/CACHEDEV1_DATA/pbtest/include/access_management.js:180:27)
    at Function.SecurityService.authenticateSession (/share/CACHEDEV1_DATA/pbtest/include/access_management.js:201:9)
    at LoginActionControllerModule.LoginActionController.onPostParamsRetrieved (/share/CACHEDEV1_DATA/pbtest/plugins/pencilblue/controllers/actions/login.js:47:21)
    at /share/CACHEDEV1_DATA/pbtest/controllers/form_controller.js:61:18
    at /share/CACHEDEV1_DATA/pbtest/controllers/base_controller.js:378:13
    at IncomingMessage.<anonymous> (/share/CACHEDEV1_DATA/pbtest/controllers/base_controller.js:438:13)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)

**Comment by brianhyder** [comment]
The supported versions of pb are listed on the Readme. We haven't had time
to invest in v5 or v6

**Comment by brianhyder** [comment]
Related to #1031

**Comment by brianhyder** [comment]
@JLKM Finally figured out what the problem is:
https://github.com/nodejs/node/wiki/Breaking-changes-between-v5-and-v6#querystring

The above is a bit annoying because it is going to cost us performance wise to set the prototype back onto the object.  I'm working now to get support for v5 & v6 working.  You can track progress on the branch feature/1031
