### ISSUE TITLE
shutdown error message

### ISSUE THREAD

**Issue by awb99** [pencilblue/pencilblue#1042]
**Description:**
On shutdown, I get this error message:
```
{"level":"info","message":"System[M]: Shutdown complete","timestamp":"2016-05-13T07:29:04.067Z"}
{"level":"error","message":"System[1]: uncaught Exception detected : Error: fakeredis: You've closed this connection with .end(), cannot quit\n    at RedisClient.cl.send_command (/data/rutadecenotes/node_modules/fakeredis/main.js:47:13)\n    at RedisClient.(anonymous function) (/data/rutadecenotes/node_modules/redis/index.js:991:25)\n    at Object.CacheModule.CacheFactory.shutdown [as CacheFactory] (/data/rutadecenotes/include/dao/cache.js:87:20)\n    at Domain.<anonymous> (/data/rutadecenotes/include/system/system.js:227:44)\n    at Domain.run (domain.js:228:14)\n    at /data/rutadecenotes/include/system/system.js:225:19\n    at /data/rutadecenotes/node_modules/async/lib/async.js:570:21\n    at /data/rutadecenotes/node_modules/async/lib/async.js:249:17\n    at /data/rutadecenotes/node_modules/async/lib/async.js:125:13\n    at Array.forEach (native)","timestamp":"2016-05-13T07:29:04.082Z"}
```

**Steps to Reproduce:**

**Configuration Details:**
Debian Jessie, with ARM processor

**Log Output:**

PencilBlue Version:  latest

Node.js Version: latest

Environment Description: ARM

**Comment by brianhyder** [comment]
This is a limitation of the fake redis module.  We've looked to solve it in 0.6.0 without much success.  When using a real redis instance the error does not occur.  I have confirmed that the error does not disrupt the shutdown processes.
