### ISSUE TITLE
sample plugin

### ISSUE THREAD

**Issue by ceballos59** [pencilblue/pencilblue#1098]
when you run http://localhost:8080/sample/random/text onto sample.js plugin.  the angular error

Failed to instantiate module pencilblueApp due to:
Error: [$injector:nomod] http://errors.angularjs.org/1.2.15/$injector/nomod?p0=pen...
    at Error (native)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:6:450
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:20:260
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:21:262
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:32:69
    at Array.forEach (native)
    at r (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:7:280)
    at e (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:32:9)
    at Zb (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:35:98)
    at c (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:17:431

displayed in console

**Comment by ceballos59** [comment]
In my version it has been tested and is now working properly. Thank you
