### ISSUE TITLE
Custom selection for SMTP - issue - doesn't allow anonymous auth connections

### ISSUE THREAD

**Issue by Karnith** [pencilblue/pencilblue#1132]
**Description:**

When choosing the custom selection for SMTP to connect to a local SMTP relay server an error is produced {"name":"AuthError","data":"504 5.7.4 Unrecognized authentication type","stage":"auth"}. If basic auth is selected then the email connection is made and sent.

SimpleSMTP (https://github.com/andris9/simplesmtp) is also no longer being supported...

"DEPRECATION NOTICE

This module is deprecated. For SMTP servers use smtp-server, for SMTP clients use smtp-connection. Alternatively, for full featured SMTP server applications, you should use Haraka."

**Steps to Reproduce:**

In an SMTP server select only anonymous auth. Configure the email setting of pb with only server name and port.

**Configuration Details:**

The SMTP server is a relay to an Office 365 exchange server, is set to only allow connections from the local net and sub net via ip access filtering, auth is set to anonymous SMTP server is a windows 2012 r2 system with IIS for the SMTP relay. In the email section of the pencilBlue site I have only the dns name of the SMTP server and port 25 configured. 

**Log Output:**

2016-08-28T19:39:07.954Z - error: [1] EmailService: Failed to send email:  AuthError: Invalid login - 504 5.7.4 Unrecognized authentication type
    at SMTPClient._actionAUTHComplete (E:\JPB\node_modules\simplesmtp\lib\client.js:925:23)
    at SMTPClient._onData (E:\JPB\node_modules\simplesmtp\lib\client.js:354:29)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)

PencilBlue Version:  0.6.1

Node.js Version: 6.3.1

Environment Description:

Windows 10 pc
Server 2012 r2 SMTP server

**Comment by brianhyder** [comment]
Thanks for the report.  We recently looked into upgrading the email service in PB.  The current issue is that there is a breaking change in our email dependency. The effort involved to upgrade forced us to move this down in our backlog.  

However, I'm happy to try and debug.  If you'd like, you can send me more details about the email server in a private message in our Gitter chat.  Additionally, you could try modifying this line:
https://github.com/pencilblue/pencilblue/blob/master/include/email.js#L128 to only add the ```auth``` block when the username and password are non-null and not empty strings.

**Comment by dukeofsussex** [comment]
Do you still want a hand on this, @brianhyder?
