### ISSUE TITLE
Page validation error

### ISSUE THREAD

**Issue by dukeofsussex** [pencilblue/pencilblue#1160]
**Description:**
Trying to create an exact duplicate of a page results in an error.

**Steps to Reproduce:**
- Create some random page
- Create a new page with the same name as the previously created one and fill in required fields
- Save
- Receive no success or error message in the admin panel, instead the log output below

This also seems to happen if the URL is already taken.

**Configuration Details:**
Default config, no plugins

**Log Output:**
```
2016-10-14T10:33:12.283Z - error: [M] RequestHandler: RangeError: Invalid status code: 11000
    at ServerResponse.writeHead (_http_server.js:192:11)
    at RequestHandlerModule.RequestHandler.writeResponse (E:\GitHub\newsletter\include\http\request_handler.js:1334:23)
    at RequestHandlerModule.RequestHandler.onRenderComplete (E:\GitHub\newsletter\include\http\request_handler.js:1274:18)
    at E:\GitHub\newsletter\include\http\request_handler.js:805:22
    at E:\GitHub\newsletter\include\error\formatters\error_formatters.js:294:13
    at ErrorFormatters.json (E:\GitHub\newsletter\include\error\formatters\error_formatters.js:98:9)
    at Function.ErrorFormatters.formatForMime (E:\GitHub\newsletter\include\error\formatters\error_formatters.js:293:9)
    at E:\GitHub\newsletter\include\http\request_handler.js:794:32
    at getActiveTheme (E:\GitHub\newsletter\include\http\request_handler.js:767:24)
    at RequestHandlerModule.RequestHandler.serveError (E:\GitHub\newsletter\include\http\request_handler.js:778:9)
```

PencilBlue Version: 0.7.0

Node.js Version: 4.4.5

Environment Description: Win Dev

**Comment by brianhyder** [comment]
NOTES:
* There is a unique index on headline for pages.  Need to check on articles.  
* The 11000 error is thrown because the mongo error objects use a ```code``` property off of the error, just like PB, to use for setting the HTTP status.  This causes conflict when the DB constraints aren't handled and prevented by the service layer and its validations.
* This most likely applies to articles because both Articles and Pages have similar validation functions.

The Fix:
* double check on article and see if the validation is needed for it too.
* Add a headline validation routine to ContentObjectService since both ArticleService and PageService extend it.  Keep things DRY.
* The validation function should verify that only a single piece of content of the specified type has that headline.  This can be done using the [DAO.unique](http://pencilblue.github.io/classes/DAO.html#method_unique) function.
* Call the validation function from the validation routine in each service (assuming applicable to both articles and pages).
