### ISSUE TITLE
class PluginInitializationService - SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by jdgomezb** [pencilblue/pencilblue#1166]
**Description:**
When trying to start PB, I get this error:

```
~/Projects/pbTest (master)
> pbctrl start
The start command is deprecated. Use `npm start` instead.
Override file [/Users/jdgomezb/Projects/pbTest/config.js] will be applied.
2016-10-25T17:15:06.131Z - info: [M] SystemStartup: Log Level is: info
/Users/jdgomezb/Projects/pbTest/include/service/entities/plugins/plugin_initialization_service.js:40
    class PluginInitializationService {
    ^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at PB (/Users/jdgomezb/Projects/pbTest/include/requirements.js:288:38)
    at new PencilBlue (/Users/jdgomezb/Projects/pbTest/pencilblue.js:47:30)
    at Function.PencilBlue.startInstance (/Users/jdgomezb/Projects/pbTest/pencilblue.js:379:25)
Failed to start PencilBlue: "Override file [/Users/jdgomezb/Projects/pbTest/config.js] will be applied.\n2016-10-25T17:15:06.131Z - info: [M] SystemStartup: Log Level is: info\n"
```

**Steps to Reproduce:**
I've created a fresh new site from the Installation guide, and also from cloning the PB github repo, and both give me the same error, even running *nodemon pencilblue* gives me the same error:

```
~/Projects/pencilblue (master)
> nodemon pencilblue
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node pencilblue ./pencilblue.js`
No overrides are available, skipping to defaults after searching the following files:
* /Users/jdgomezb/Projects/pencilblue/config.js
* /etc/pencilblue/config.js
2016-10-25T15:49:40.437Z - info: [M] SystemStartup: Log Level is: info
/Users/jdgomezb/Projects/pencilblue/include/service/entities/plugins/plugin_initialization_service.js:40
    class PluginInitializationService {
    ^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at PB (/Users/jdgomezb/Projects/pencilblue/include/requirements.js:288:38)
    at new PencilBlue (/Users/jdgomezb/Projects/pencilblue/pencilblue.js:47:30)
    at Function.PencilBlue.startInstance (/Users/jdgomezb/Projects/pencilblue/pencilblue.js:379:25)
[nodemon] app crashed - waiting for file changes before starting...
```

**PencilBlue Version:**
```0.7.0```

**Node.js Version:**
```> node --version
v0.12.6```

**Environment Description:**
Macbook Pro 13-inch Mid 2012
OS X El Capitan

**Comment by dukeofsussex** [comment]
Try upgrading to a 4.x version of Node. I'm running 4.4.7 and PB works fine :)

**Comment by jdgomezb** [comment]
Yes, that fixed my issue, thanks @dukeofsussex
