### ISSUE TITLE
Public Route 404's hang page loads

### ISSUE THREAD

**Issue by lgenet** [pencilblue/pencilblue#1208]
**Description:**
When loading a page, if I have a script tag that is to load a bower component, if that component does not exist, then we get a 404 as expected.  However, we get an uncaught exception which dumps us into the domains "error" block and then the request is left to starve.  The reason for this is the topic of the issue.

**Steps to Reproduce:**
put a script tag to a bower resource that does not exist on your page.  
```<script src="/bower_components/myFakeResource.js"></script>``` And load that page.

**Configuration Details:**
 Local, running in multisite mode

**Log Output:**
```
2017-01-24T14:09:05.024Z - error: [1] Router: An unhandled error occurred after calling middleware "initializeController": TypeError: Cannot read property 'language' of undefined
    at NotFoundController.BaseControllerModule.BaseController.getTemplateServiceInstance (/Users/logenet/Documents/Node Projects/CMSPencilblue/controllers/base_controller.js:277:31)
    at NotFoundController.BaseControllerModule.BaseController.init (/Users/logenet/Documents/Node Projects/CMSPencilblue/controllers/base_controller.js:208:24)
    at NotFoundController.ErrorViewController.init (/Users/logenet/Documents/Node Projects/CMSPencilblue/controllers/error_controller.js:81:51)
    at NotFoundControllerModule.NotFoundController.init (/Users/logenet/Documents/Node Projects/CMSPencilblue/plugins/pencilblue/controllers/error/404.js:54:48)
    at initializeController (/Users/logenet/Documents/Node Projects/CMSPencilblue/include/http/middleware/index.js:439:36)
    at execute (/Users/logenet/Documents/Node Projects/CMSPencilblue/include/http/router.js:90:17)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickDomainCallback (node.js:390:13)
```

***Additional Findings***
From the error, it is not obvious that this is an issue with public routes 404ing.  Through debugging I was able to shed a little more light on the core problem (or what I think is the core issue).  When the public route is not found, the serve404 method is called, which calls serve error.  When this is called, it builds up some context on requestHandler and then passes it to the middleware stack after the "parseBody" step.  

Durring the initialize controller step of the middleware stack, before .init is called for the errorController, the props object is built from the request.  However, most of the things that props tries to get from req are undefined, but they do exist on req.handler (since we built that out durring the serve error function/flow)  

I am unsure whether just ORing the props builder to examine both req and req.handler is the optimal solution, or if there is a better place to handle this.

The actual error that hits the console is because props is not well defined, when we go into base controller, we try to do self.ls.language, and self.ls is undefined because props.ls is undefined.

PencilBlue Version: 0.8.0

Node.js Version: 4.2.2

Environment Description: Mac OSX

**Comment by blakecallens** [comment]
This is a bit deeper than what's in the console. Still looking into it. I fixed the undefined variable bug, but then I get an error where the base controller isn't being properly initialized. Looking into it still.

**Comment by lgenet** [comment]
If I can be of any further assistance please let me know :)

**Comment by blakecallens** [comment]
@brianhyder this is definitely something around the base controller not initializing properly. Not sure where that might be happening.

**Comment by brianhyder** [comment]
@blakecallens @lgenet I spent some time this morning diving into this one.  The crux of it is that the serving up of public routes does not follow the same request pipeline as all other requests.  This means that all of the route lookup, localization, and other goodies are not available when things go wrong.  

The fix I have on branch *issue/1208* fools the request handler into thinking that the request has an expected content type for the requested route of ```application/json```.  We do this because we do not need a controller to serialize the output.  Additionally, this keeps the response size minimal during an error.  

I made notes in the fix that this is a point of refactor for the 1.0 release.  Good catch, @lgenet.  I'll have a PR up momentarily.

**Comment by lgenet** [comment]
@brianhyder Found this... 

```error: Router: An unhandled error occurred after calling middleware "deriveActiveTheme": TypeError: Cannot assign to read only property 'content_type' of #<Object>
    at ReadFileContext.<anonymous> (/Users/logenet/Documents/Node Projects/CMSPencilblue/include/http/request_handler.js:715:46)
    at ReadFileContext.callback (/Users/logenet/Documents/Node Projects/CMSPencilblue/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
2017-02-02T14:20:48.115Z - error: [1] Router: An unhandled error occurred after calling middleware "deriveActiveTheme": TypeError: Cannot assign to read only property 'content_type' of #<Object>
    at ReadFileContext.<anonymous> (/Users/logenet/Documents/Node Projects/CMSPencilblue/include/http/request_handler.js:715:46)
    at ReadFileContext.callback (/Users/logenet/Documents/Node Projects/CMSPencilblue/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
error: System[1]: uncaught Exception detected : TypeError: Cannot assign to read only property 'content_type' of #<Object>
    at ReadFileContext.<anonymous> (/Users/logenet/Documents/Node Projects/CMSPencilblue/include/http/request_handler.js:715:46)
    at ReadFileContext.callback (/Users/logenet/Documents/Node Projects/CMSPencilblue/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
2017-02-02T14:20:48.762Z - error: [1] System[1]: uncaught Exception detected : TypeError: Cannot assign to read only property 'content_type' of #<Object>
    at ReadFileContext.<anonymous> (/Users/logenet/Documents/Node Projects/CMSPencilblue/include/http/request_handler.js:715:46)
    at ReadFileContext.callback (/Users/logenet/Documents/Node Projects/CMSPencilblue/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)```

**Comment by brianhyder** [comment]
When it rains it pours. This is because we froze the route object. Should
be an easy fix to clone the object and set the content type. I can take a
look to verify this evening.   My apologies for missing that.

**Comment by lgenet** [comment]
You are fine my friend.  Just thought I would let you know.  I temporarily patched it on my end by commenting out the offending line.  (the setting application/json) and it runs again.  If you need anything else from me let me know.

**Comment by sambostock** [comment]
@lgenet Can you elaborate on your temporary patch?

**Comment by lgenet** [comment]
@sambostock I simply commented out the line that is currently cause failures in this context.  code below.

```
    RequestHandler.prototype.servePublicContent = function(absolutePath) {

        //check for provided path, then default if necessary
        if (util.isNullOrUndefined(absolutePath)) {
            absolutePath = path.join(pb.config.docRoot, 'public', this.url.pathname);
        }

        var self = this;
        fs.readFile(absolutePath, function(err, content){
            if (err) {

                //TODO [1.0] change default content type to JSON and refactor public file serving so it falls inline with other controller functions
                self.themeRoute = self.themeRoute || {};
//                self.themeRoute.content_type = 'application/json';  // This is the line I commented out.
                return self.serve404();
            }
```

**Comment by brianhyder** [comment]
Hey all,  testing a fix now.  I've modified the block such that it will taken the frozen themeRoute object and clone it such that the content_type can be reassigned.

**Comment by brianhyder** [comment]
@lgenet, just so I can verify the fix.  What route were you trying to hit when it failed?

**Comment by brianhyder** [comment]
suggested fix is up on branch [issue/1208](https://github.com/pencilblue/pencilblue/tree/issue/1208)

**Comment by lgenet** [comment]
in my case, I hit /join which has an unstable bower component that often times fails to install correctly.  where /join is a custom defined route.  But I have reproduced this on a pencilblue (as active theme) landing page.  by adding a dummy public script tag :)
