### ISSUE TITLE
Pencilblue with Passenger

### ISSUE THREAD

**Issue by amfolgar** [pencilblue/pencilblue#1249]
**Description:**
This is the first time I open an issue, so I apologise in advance.
I'm trying to run pencilblue with Passenger and Apache on Debian 8 but it doesn't work. If I launch from the terminal the command `npm start` it works perfectly. 

**Steps to Reproduce:**
I don't know what to write here exactly, the debian,apache,passenger, etc is already installed and configured in the server by default, I just try to install the cms following the instructions I've found on the wiki, and trying options I saw in others issues or webs.

**Configuration Details:**
This is the config.js I'm using, copied from here: https://github.com/pencilblue/pencilblue/issues/956#issuecomment-209172749:

module.exports = {
    "siteName": "My PencilBlue Site",
    "siteRoot": "http://myblog.com/pencilblue/",
    "logging": {
        "level": "silly"
    },
    "db": {
	name: "dbpencilblue",
        servers: [
            "mongodb.server.com:27017"
        ],
	"authentication": {
            "un": "user-db",
            "pw": "pass-db"
        }
    },
    server: {
      ssl: {
          enabled: false,
          use_x_forwarded_for: false
      }
  },
    "cluster": {
        "self_managed": false
    }
};

**Log Output:**
In the log/pencilblue.log there is no error. 
In the log of apache I can see this:

[ 2017-04-11 20:04:39.1275 18841/7f1b74139700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /home/myblog/pencilblue/: An error occurred while starting the web application: it did not write a startup response in time.

PencilBlue Version: 
I don't know how to check the version, but I downloaded the repo today, so it has to be the latest version.
 
Node.js Version:
v6.9.4

Environment Description:
Debian 8
Apache 2.4.10 
Phusion Passenger 5.1.0
Mongodb 2.6.7

**Comment by brianhyder** [comment]
I've never used passenger before so I don't know what it is looking for as its "startup response".  If you can provide that detail we might be able to help further.

**Comment by amfolgar** [comment]
The app should send some kind of response to Passenger, according to the documentation of Passenger 'Phusion Passenger reports this error if the application did not finish initializing within a time limit, or if it exited without sending Phusion Passenger a message that says "I've initialized successfully!".'

I found a similar problem where the app didn't send this 'initialized successfully' to Passenger, and they could fix it; this is the thread, refered to a ruby app, but in this response there's a link to nodejs app with the same problem: https://github.com/phusion/passenger-docker/issues/40#issuecomment-53046885

I tried to add the app.listen() commented in the answer to the pencilblue.js file, below the line  PencilBlue.startInstance();, but doing this I get this error when launching with the npm start command:

2017-04-12T10:06:40.379Z - error: [M] System[M]: uncaught Exception detected : ReferenceError: app is not defined
    at Object.<anonymous> (/home/myblog/pencilblue/pencilblue.js:402:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

I made a rgrep to the code looking for app.listen() in the code, but I found it in some example files and readme. Do you know where can I try to put the line?
