### ISSUE TITLE
After wordpress import, pages will no longer delete

### ISSUE THREAD

**Issue by caseyctg** [pencilblue/pencilblue#422]
After using the wordpress import, the page delete will no longer function. It pops up the dialog and acts like it's deleting, but it never deletes the page. 

![screen shot 2015-01-06 at 8 53 00 pm](https://cloud.githubusercontent.com/assets/4631889/5640051/0911ddaa-95e6-11e4-9bd8-c005b0d9de56.png)
![screen shot 2015-01-06 at 8 53 12 pm](https://cloud.githubusercontent.com/assets/4631889/5640052/0a747cca-95e6-11e4-88f7-9894aeeeb4d0.png)

**Comment by caseyctg** [comment]
Cloned from master branch on Jan 5 - v0.3.0. Local install.

**Comment by caseyctg** [comment]
Error: collection name must be a String
    at Error (<anonymous>)
    at Object.checkCollectionName (/Users/xxxxxxxxxx/Documents/pencilblue-master/pencilblue/node_modules/mongodb/lib/mongodb/collection/shared.js:65:11)
    at new Collection (/Users/xxxxxxxxxx/Documents/pencilblue-master/pencilblue/node_modules/mongodb/lib/mongodb/collection.js:44:10)
    at Db.collection (/Users/xxxxxxxxxx/Documents/pencilblue-master/pencilblue/node_modules/mongodb/lib/mongodb/db.js:497:24)
    at DAO._doQuery (/Users/xxxxxxxxxx/Documents/pencilblue-master/pencilblue/include/dao/dao.js:318:35)
    at DAO.q (/Users/xxxxxxxxxx/Documents/pencilblue-master/pencilblue/include/dao/dao.js:263:23)
    at DAO.loadByValues (/Users/xxxxxxxxxx/Documents/pencilblue-master/pencilblue/include/dao/dao.js:134:10)
    at DAO.loadById (/Users/xxxxxxxxxx/Documents/pencilblue-master/pencilblue/include/dao/dao.js:92:10)
    at DeletePage.render (/Users/xxxxxxxxxx/Documents/pencilblue-master/pencilblue/plugins/pencilblue/controllers/actions/admin/content/pages/delete_page.js:41:9)
    at /Users/xxxxxxxxxx/Documents/pencilblue-master/pencilblue/include/http/request_handler.js:764:75
error: collection name must be a String    at Error (<anonymous>)    at Object.checkCollectionName (/Users/xxxxxxxxxx/Documents/pencilblue-master/pencilblue/node_modules/mongodb/lib/mongodb/collection/shared.js:65:11)    at new Collection (/Users/xxxxxxxxxx/Documents/pencilblue-master/pencilblue/node_modules/mongodb/lib/mongodb/collection.js:44:10)    at Db.collection (/Users/xxxxxxxxxx/Documents/pencilblue-master/pencilblue/node_modules/mongodb/lib/mongodb/db.js:497:24)    at DAO._doQuery (/Users/xxxxxxxxxx/Documents/pencilblue-master/pencilblue/include/dao/dao.js:318:35)    at DAO.q (/Users/xxxxxxxxxx/Documents/pencilblue-master/pencilblue/include/dao/dao.js:263:23)    at DAO.loadByValues (/Users/xxxxxxxxxx/Documents/pencilblue-master/pencilblue/include/dao/dao.js:134:10)    at DAO.loadById (/Users/xxxxxxxxxx/Documents/pencilblue-master/pencilblue/include/dao/dao.js:92:10)    at DeletePage.render (/Users/xxxxxxxxxx/Documents/pencilblue-master/pencilblue/plugins/pencilblue/controllers/actions/admin/content/pages/delete_page.js:41:9)    at /Users/xxxxxxxxxx/Documents/pencilblue-master/pencilblue/include/http/request_handler.js:764:75

**Comment by brianhyder** [comment]
Fixed.  I broke that recently while removing deprecated functions.  Good catch and thanks for reporting.

**Comment by caseyctg** [comment]
That fixed it. Thanks!
