### ISSUE TITLE
MongoError: no such cmd: collMod

### ISSUE THREAD

**Issue by gauravt** [pencilblue/pencilblue#451]
I am getting this error whenever I'm trying to run the application:

domain.js:66
    throw er;
          ^
MongoError: no such cmd: collMod
    at Object.toError (/home/gauravt/Desktop/BohoStar/pblue/node_modules/mongodb/lib/mongodb/utils.js:114:11)
    at Db.command (/home/gauravt/Desktop/BohoStar/pblue/node_modules/mongodb/lib/mongodb/db.js:1165:31)
    at Db._executeQueryCommand (/home/gauravt/Desktop/BohoStar/pblue/node_modules/mongodb/lib/mongodb/db.js:1874:9)
    at Server.Base._callHandler (/home/gauravt/Desktop/BohoStar/pblue/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at Server.connect.connectionPool.on.server._serverState (/home/gauravt/Desktop/BohoStar/pblue/node_modules/mongodb/lib/mongodb/connection/server.js:481:18)
    at MongoReply.parseBody (/home/gauravt/Desktop/BohoStar/pblue/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at Server.connect.connectionPool.on.server._serverState (/home/gauravt/Desktop/BohoStar/pblue/node_modules/mongodb/lib/mongodb/connection/server.js:439:20)
    at EventEmitter.emit (events.js:88:17)
    at _connect (/home/gauravt/Desktop/BohoStar/pblue/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)
    at EventEmitter.emit (events.js:91:17)

**Comment by brianhyder** [comment]
What version of Mongo are you using? What version of the Mongo node driver
is in the node_modules directory for the pencilblue installation?
These two items will help narrow it down.

**Comment by gauravt** [comment]
Problem was with old node.js version, solved by updating. Thanks
