### ISSUE TITLE
Issue deploying pencilblue with nodemon

### ISSUE THREAD

**Issue by misbahneo** [pencilblue/pencilblue#485]
Hi I've looked over the other issues here and couldnt see an answer so sorry if this has been asked before

trying to run pencilblue after installing into the correct directory, I have all the correct files but when i try and run pencil blue I get this error

```
Misbahs-MacBook-Pro:misdigest misbahanjum-james$ nodemon pencilblue.js
3 Mar 13:00:23 - [nodemon] v1.3.7
3 Mar 13:00:23 - [nodemon] to restart at any time, enter `rs`
3 Mar 13:00:23 - [nodemon] watching: *.*
3 Mar 13:00:23 - [nodemon] starting `node pencilblue.js`
SystemStartup: Override file [/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/config.json] will be applied.
SystemStartup: Log Level is: info
2015-03-03T13:00:25.581Z - info: [M] System[M]: 1 workers spawned. Listening for disconnects.
SystemStartup: Override file [/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/config.json] will be applied.
SystemStartup: Log Level is: info

/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/node_modules/mongodb/lib/mongodb/mongo_client.js:409
          throw err
                ^
Error: failed to connect to [127.0.0.1:27017]
    at null.<anonymous> (/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/node_modules/mongodb/lib/mongodb/connection/server.js:549:74)
    at emit (events.js:106:17)
    at null.<anonymous> (/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickDomainCallback (node.js:486:13)
SystemStartup: Override file [/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/config.json] will be applied.
SystemStartup: Log Level is: info

/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/node_modules/mongodb/lib/mongodb/mongo_client.js:409
          throw err
                ^
Error: failed to connect to [127.0.0.1:27017]
    at null.<anonymous> (/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/node_modules/mongodb/lib/mongodb/connection/server.js:549:74)
    at emit (events.js:106:17)
    at null.<anonymous> (/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickDomainCallback (node.js:486:13)
SystemStartup: Override file [/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/config.json] will be applied.
SystemStartup: Log Level is: info

/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/node_modules/mongodb/lib/mongodb/mongo_client.js:409
          throw err
                ^
Error: failed to connect to [127.0.0.1:27017]
    at null.<anonymous> (/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/node_modules/mongodb/lib/mongodb/connection/server.js:549:74)
    at emit (events.js:106:17)
    at null.<anonymous> (/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickDomainCallback (node.js:486:13)
SystemStartup: Override file [/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/config.json] will be applied.
SystemStartup: Log Level is: info

/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/node_modules/mongodb/lib/mongodb/mongo_client.js:409
          throw err
                ^
Error: failed to connect to [127.0.0.1:27017]
    at null.<anonymous> (/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/node_modules/mongodb/lib/mongodb/connection/server.js:549:74)
    at emit (events.js:106:17)
    at null.<anonymous> (/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickDomainCallback (node.js:486:13)
SystemStartup: Override file [/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/config.json] will be applied.
SystemStartup: Log Level is: info

/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/node_modules/mongodb/lib/mongodb/mongo_client.js:409
          throw err
                ^
Error: failed to connect to [127.0.0.1:27017]
    at null.<anonymous> (/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/node_modules/mongodb/lib/mongodb/connection/server.js:549:74)
    at emit (events.js:106:17)
    at null.<anonymous> (/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickDomainCallback (node.js:486:13)
SystemStartup: Override file [/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/config.json] will be applied.
SystemStartup: Log Level is: info

/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/node_modules/mongodb/lib/mongodb/mongo_client.js:409
          throw err
                ^
Error: failed to connect to [127.0.0.1:27017]
    at null.<anonymous> (/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/node_modules/mongodb/lib/mongodb/connection/server.js:549:74)
    at emit (events.js:106:17)
    at null.<anonymous> (/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickDomainCallback (node.js:486:13)
SystemStartup: Override file [/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/config.json] will be applied.
SystemStartup: Log Level is: info
```

Here is what my config.json file looks like, happy to provde any other details i might be missing because it seems like the install should be fairly simple so I feel like im being stupid.

```
{
    "siteName": "misdigest",
    "siteRoot": "http://127.0.0.1:8080",
    "sitePort": 8080,
    "log_level": "info",
    "db": {
        "type":"mongo",
        "servers": [
          "127.0.0.1:27017"
        ],
        "name": "pencilblue",
        "writeConcern": 1
    },
    "cache": {
        "fake": true,
        "host": "localhost",
        "port": 6379
    },
    "settings": {
        "use_memory": false,
        "use_cache": false
    },
    "templates": {
        "use_memory": true,
        "use_cache": false
    },
    "plugins": {
        "caching": {
            "use_memory": false,
            "use_cache": false
        }
    },
    "registry": {
        "type": "mongo"
    },
    "session": {
        "storage": "mongo"
    }
}

```

**Comment by brianhyder** [comment]
It appears that Mongo DB isn't running

**Comment by misbahneo** [comment]
thank you for the swift reply will try and make sure mongo is running

**Comment by brianhyder** [comment]
Np, let us know if that doesn't do it.

**Comment by misbahneo** [comment]
So i managed to get mongodb running but now It say's this, is this to do with my config.json file then?

```
Last login: Tue Mar  3 13:15:09 on ttys000
Misbahs-MacBook-Pro:~ misbahanjum-james$ cd /Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest 
Misbahs-MacBook-Pro:misdigest misbahanjum-james$ nodemon pencilblue.js
3 Mar 13:23:01 - [nodemon] v1.3.7
3 Mar 13:23:01 - [nodemon] to restart at any time, enter `rs`
3 Mar 13:23:01 - [nodemon] watching: *.*
3 Mar 13:23:01 - [nodemon] starting `node pencilblue.js`
SystemStartup: Override file [/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/config.json] will be applied.
SystemStartup: Log Level is: info
2015-03-03T13:23:12.049Z - info: [M] System[M]: 1 workers spawned. Listening for disconnects.
SystemStartup: Override file [/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/config.json] will be applied.
SystemStartup: Log Level is: info
2015-03-03T13:23:17.485Z - info: [1] PencilBlue: Ensuring indices...

/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/pencilblue.js:49
			throw err;
			      ^
Error: Failed to start HTTP server on PORT=[8080] binding to SITE_IP=[0.0.0.0]: bind EADDRINUSE
    at errnoException (net.js:905:11)
    at net.js:1085:30
    at Object.1:1 (cluster.js:594:5)
    at handleResponse (cluster.js:171:41)
    at respond (cluster.js:192:5)
    at handleMessage (cluster.js:202:5)
    at process.emit (events.js:117:20)
    at handleMessage (child_process.js:322:10)
    at child_process.js:396:7
    at process.handleConversion.net.Native.got (child_process.js:91:7)
SystemStartup: Override file [/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/config.json] will be applied.
SystemStartup: Log Level is: info
2015-03-03T13:23:19.107Z - info: [2] PencilBlue: Ensuring indices...

/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/pencilblue.js:49
			throw err;
			      ^
Error: Failed to start HTTP server on PORT=[8080] binding to SITE_IP=[0.0.0.0]: bind EADDRINUSE
    at errnoException (net.js:905:11)
    at net.js:1085:30
    at Object.2:1 (cluster.js:594:5)
    at handleResponse (cluster.js:171:41)
    at respond (cluster.js:192:5)
    at handleMessage (cluster.js:202:5)
    at process.emit (events.js:117:20)
    at handleMessage (child_process.js:322:10)
    at child_process.js:396:7
    at process.handleConversion.net.Native.got (child_process.js:91:7)
SystemStartup: Override file [/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/config.json] will be applied.
SystemStartup: Log Level is: info
2015-03-03T13:23:20.289Z - info: [3] PencilBlue: Ensuring indices...

/Users/misbahanjum-james/Documents/University/year3/project/misdigest/misdigest/pencilblue.js:49
			throw err;

```

**Comment by brianhyder** [comment]
Yes and no.  The ```EADDRINUSE``` error means that another process is already listening on port 8080.  You can kill off this process or change the port and siteRoot properties in your config.js file to something like ```8081``` and it should run.

**Comment by misbahneo** [comment]
ah perfect I was just about to say It IS actually now up and running so i guess that isn't a fatal error

**Comment by misbahneo** [comment]
Thank you! I suppose you couldnt tell me the command to stop running pencilblue?

**Comment by misbahneo** [comment]
you guys are stars!

**Comment by brianhyder** [comment]
There isn't a ui command. However, in your console, you do ctrl+c and PB
will catch the SIGTERM signal and enter the shutdown process.
