### ISSUE TITLE
Bug: Removing Child Navigation item throws error

### ISSUE THREAD

**Issue by cchatham** [pencilblue/pencilblue#557]
To reproduce:
- Go to Admin console > Content > Navigation
- Remove a child Nav item from a Container type Nav item.
- Go to Home page of site.
- This error occurs:
```
TypeError: Cannot read property 'active' of null
  at /Users/cchatham/repos/pencilblue/include/service/entities/section_service.js:264:42
  at /Users/cchatham/repos/pencilblue/include/dao/dao.js:270:17
  at handleCallback (/Users/cchatham/repos/pencilblue/node_modules/mongodb/lib/utils.js:95:12)
  at /Users/cchatham/repos/pencilblue/node_modules/mongodb/lib/cursor.js:571:16
  at handleCallback (/Users/cchatham/repos/pencilblue/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:234:5)
  at setCursorDeadAndNotified (/Users/cchatham/repos/pencilblue/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:424:3)
  at [object Object].Cursor.next (/Users/cchatham/repos/pencilblue/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:585:7)
  at fetchDocs (/Users/cchatham/repos/pencilblue/node_modules/mongodb/lib/cursor.js:567:10)
  at /Users/cchatham/repos/pencilblue/node_modules/mongodb/lib/cursor.js:583:7
  at handleCallback (/Users/cchatham/repos/pencilblue/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:234:5)
  at [object Object].Cursor.next (/Users/cchatham/repos/pencilblue/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:603:5)
  at /Users/cchatham/repos/pencilblue/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:540:12
  at queryCallback (/Users/cchatham/repos/pencilblue/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:215:5)
  at bound (domain.js:254:14)
  at runBound (domain.js:267:12)
  at [object Object].Callbacks.emit (/Users/cchatham/repos/pencilblue/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:84:3)
  at [object Object].messageHandler (/Users/cchatham/repos/pencilblue/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:218:23)
  at Socket. (/Users/cchatham/repos/pencilblue/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:259:22)
  at Socket.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:163:16)
  at Socket.Readable.push (_stream_readable.js:126:10)
  at TCP.onread (net.js:529:20)
```

**Comment by cchatham** [comment]
So weird thing. If I go back in and click on save in the navigation the error goes away. I'm confused. Why do I have to save a deletion?

**Comment by brianhyder** [comment]
This is a confirmed bug.  I'm going to look into it.  You shouldn't have to click save.  My guess is that the section map isn't being updated appropriately after the child has been removed.
