### ISSUE TITLE
Media Provider Error on site update

### ISSUE THREAD

**Issue by JahlomP** [pencilblue/pencilblue#597]
Whenever I update my site on heroku, the first request gives me this error in the browser:
`Whoops! Something unexpected happened.

Error: A valid media provider is required. Please check your configuration
    at new MediaService (/app/include/service/entities/media_service.js:40:19)
    at /app/include/service/entities/article_service.js:597:22
    at /app/include/dao/dao.js:142:12
    at /app/include/dao/dao.js:270:17
    at handleCallback (/app/node_modules/mongodb/lib/utils.js:95:12)
    at /app/node_modules/mongodb/lib/cursor.js:571:16
    at handleCallback (/app/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:234:5)
    at setCursorDeadAndNotified (/app/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:424:3)
    at Cursor.next (/app/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:543:14)
    at fetchDocs (/app/node_modules/mongodb/lib/cursor.js:567:10)
`

The following request works fine. @blakecallens @brianhyder, what is causing this?

**Comment by brianhyder** [comment]
What url are you trying to access? My guess is something is accessing the
media provider without an instance already setup.

**Comment by brianhyder** [comment]
@JahlomP Did you figure this out?  What media provider do you have configured?  Also, if you are still having issues send us the log output in silly mode.  We should be able to tell what paths it is trying when it attempts to load a media provider.

**Comment by JahlomP** [comment]
http://hugemap.info/. I am using Dropbox and I pull media on home page so i
when i visit homepage after update or server(heroku) waking from sleep,
that is when I get the error.

Will send the silly for analysis.

**Comment by JahlomP** [comment]
![untitled](https://cloud.githubusercontent.com/assets/4746511/7642610/f38de54a-fa81-11e4-8f50-f894ecd3af13.png)

**Comment by brianhyder** [comment]
The screenshot doesn't give us anything different.  We need the console output.

**Comment by vuvojunior** [comment]
Hi @brianhyder 
I got the same issue . and here are the stack trace.
```
Whoops! Something unexpected happened.


Error: A valid media provider is required. Please check your configuration
    at new MediaService (/app/include/service/entities/media_service.js:40:19)
    at new MediaLoader (/app/include/service/entities/article_service.js:551:29)
    at ArticleRenderer.formatMediaReferences (/app/include/service/entities/content/article_renderer.js:102:27)
    at /app/include/util.js:187:14
    at /app/node_modules/async/lib/async.js:570:21
    at /app/node_modules/async/lib/async.js:249:17
    at /app/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/app/node_modules/async/lib/async.js:46:24)
    at async.each (/app/node_modules/async/lib/async.js:124:9)

```
Steps to reproduce 
* Install pencilblue
* Install MediaS3 plugin
* Restart pencliblue.
Penciblue will get above stack trace at first accessing. next time it works fine

**Comment by vuvojunior** [comment]
A captured log from my server

2015-07-13T10:21:33.567142+00:00 app[web.1]: 2015-07-13T10:21:33.566Z - error: [1] RequestHandler: An error occurred during controller execution. URL=[GET:/] ROUTE={"path":"","pattern":"^/[/]{0,1}$","path_vars":{},"expression":{},"themes":{"pencilblue":{"GET":{"method":"GET","path":"/","access_level":0,"auth_required":false,"content_type":"text/html"}}}}
2015-07-13T10:21:33.567146+00:00 app[web.1]: Error: A valid media provider is required. Please check your configuration
2015-07-13T10:21:33.567147+00:00 app[web.1]:     at new MediaService (/app/include/service/entities/media_service.js:40:19)
2015-07-13T10:21:33.567149+00:00 app[web.1]:     at new MediaLoader (/app/include/service/entities/article_service.js:551:29)
2015-07-13T10:21:33.567153+00:00 app[web.1]:     at /app/include/util.js:187:14
2015-07-13T10:21:33.567154+00:00 app[web.1]:     at /app/node_modules/async/lib/async.js:570:21
2015-07-13T10:21:33.567151+00:00 app[web.1]:     at ArticleRenderer.formatMediaReferences (/app/include/service/entities/content/article_renderer.js:102:27)
2015-07-13T10:21:33.567157+00:00 app[web.1]:     at /app/node_modules/async/lib/async.js:125:13
2015-07-13T10:21:33.567160+00:00 app[web.1]:     at _each (/app/node_modules/async/lib/async.js:46:24)
2015-07-13T10:21:33.567159+00:00 app[web.1]:     at Array.forEach (native)
2015-07-13T10:21:33.567155+00:00 app[web.1]:     at /app/node_modules/async/lib/async.js:249:17
2015-07-13T10:21:33.567161+00:00 app[web.1]:     at async.each (/app/node_modules/async/lib/async.js:124:9)
2015-07-13T10:21:33.522959+00:00 app[web.1]: 2015-07-13T10:21:33.522Z - error: [1] RequestHandler: An error occurred during controller execution. URL=[GET:/] ROUTE={"path":"","pattern":"^/[/]{0,1}$","path_vars":{},"expression":{},"themes":{"pencilblue":{"GET":{"method":"GET","path":"/","access_level":0,"auth_required":false,"content_type":"text/html"}}}}
2015-07-13T10:21:33.522965+00:00 app[web.1]:     at new MediaService (/app/include/service/entities/media_service.js:40:19)
2015-07-13T10:21:33.522964+00:00 app[web.1]: Error: A valid media provider is required. Please check your configuration
2015-07-13T10:21:33.522967+00:00 app[web.1]:     at new MediaLoader (/app/include/service/entities/article_service.js:551:29)
2015-07-13T10:21:33.522969+00:00 app[web.1]:     at ArticleRenderer.formatMediaReferences (/app/include/service/entities/content/article_renderer.js:102:27)
2015-07-13T10:21:33.522971+00:00 app[web.1]:     at /app/include/util.js:187:14
2015-07-13T10:21:33.522972+00:00 app[web.1]:     at /app/node_modules/async/lib/async.js:570:21
2015-07-13T10:21:33.522974+00:00 app[web.1]:     at /app/node_modules/async/lib/async.js:249:17
2015-07-13T10:21:33.522975+00:00 app[web.1]:     at /app/node_modules/async/lib/async.js:125:13
2015-07-13T10:21:33.522977+00:00 app[web.1]:     at Array.forEach (native)
2015-07-13T10:21:33.522978+00:00 app[web.1]:     at _each (/app/node_modules/async/lib/async.js:46:24)
2015-07-13T10:21:33.522979+00:00 app[web.1]:     at async.each (/app/node_modules/async/lib/async.js:124:9)
2015-07-13T10:21:33.562570+00:00 app[web.1]: 2015-07-13T10:21:33.562Z - warn: [1] PencilBlue: pb.users is deprecated.  Use new pb.UserService(context) instead

**Comment by brianhyder** [comment]
Thank you for the additional information.  Would you mind also providing the following information?

* The environment you are deploying to (heroku, local, linux, windows, etc).
* Your config.js minus any credentials
* Are you working off of master or a different tag?
* Node.js version of the deployment environment

**Comment by brianhyder** [comment]
I haven't had a chance to prove it but what I think is happening is that your free heroku dyno is going to sleep.  When it sleeps I'm guessing that the VM or container it is running in dies.  When this happens the plugin dependencies for the S3 or dropbox plugins, that were downloaded, are wiped out.  

When traffic hits the container the application restarts.  The startup sequence starts the server first and then fires up the plugins.  When this happens the server begins to field requests ahead of the plugin initialization which must go back to NPM in order to download the dependencies.  

Seems to be a race condition.  Would either of you be willing to test out the theory by modifying the startup sequence in pencilblue.js such the that server initialization is the last piece to be called.  Basically, move line 60 (initServer) to be the last task?

**Comment by vuvojunior** [comment]
ok, let do with our theory and see next few days

**Comment by JahlomP** [comment]
@brianhyder if the theory proofs right, will the solution to the problem be added to pencilblue itself?
hope you understand.

**Comment by brianhyder** [comment]
Yes, if you can test it, find that it works, and submit a pull request into
0.4.1 we will merge it.
