### ISSUE TITLE
Err: Undefined property 'keyword' on startup.

### ISSUE THREAD

**Issue by glymehrvrd** [pencilblue/pencilblue#600]
Hello, I initialized pencilblue following the `Quickstart guide`, but after I completed the setup and viewed the site, it complained:
```
Whoops! Something unexpected happened.
TypeError: Cannot read property 'keywords' of undefined
    at /home/glyme/WebstormProjects/pb/plugins/pencilblue/controllers/index.js:51:64
    at ArticleServiceModule.ArticleService.getMetaInfo (/home/glyme/WebstormProjects/pb/include/service/entities/article_service.js:479:20)
    at /home/glyme/WebstormProjects/pb/plugins/pencilblue/controllers/index.js:50:32
    at /home/glyme/WebstormProjects/pb/node_modules/async/lib/async.js:592:17
    at done (/home/glyme/WebstormProjects/pb/node_modules/async/lib/async.js:135:19)
    at /home/glyme/WebstormProjects/pb/node_modules/async/lib/async.js:32:16
    at /home/glyme/WebstormProjects/pb/node_modules/async/lib/async.js:589:21
    at /home/glyme/WebstormProjects/pb/plugins/pencilblue/controllers/index.js:196:21
    at /home/glyme/WebstormProjects/pb/plugins/pencilblue/controllers/index.js:387:17
    at /home/glyme/WebstormProjects/pb/include/theme/top_menu.js:224:21
```
What's going wrong? Any answer would be appreciated.

**Comment by glymehrvrd** [comment]
The question got solved after I inserted an article, but I think there should be no error even if there are no article..

**Comment by brianhyder** [comment]
I recently fixed an issue in the ArticleService.  In doing so I failed to provide backward compatibility for an error case.  The code for backward compatibility has been added and will be merged after the build completes.

**Comment by brianhyder** [comment]
Thank you for reporting
