### ISSUE TITLE
0.5.0 Error on localize

### ISSUE THREAD

**Issue by btidwell** [pencilblue/pencilblue#734]
We are calling localize "content.content = self.ls.localize([], content, self.hostname);" and are randomly seeing the below error being thrown.  It looks like language is being set to 'en_US' by the 'best()' function of the locale module for some users.  This isn't happening for everyone.  

Error: Failed to set a language. LANG='en_US'
at LocalizationModule.Localization.localize (/var/app/current/include/localization.js:107:19)
at /var/app/current/plugins/careerbuilder_careers/controllers/index.js:241:35
at MediaLoader.ArticleServiceModule.MediaLoader.start (/var/app/current/include/service/entities/article_service.js:575:20)
at loadHomePageMedia (/var/app/current/plugins/careerbuilder_careers/controllers/index.js:231:19)
at /var/app/current/plugins/careerbuilder_careers/controllers/index.js:142:11
at /var/app/current/node_modules/async/lib/async.js:592:17
at done (/var/app/current/node_modules/async/lib/async.js:135:19)
at /var/app/current/node_modules/async/lib/async.js:32:16
at /var/app/current/node_modules/async/lib/async.js:589:21
at /var/app/current/plugins/careerbuilder_careers/controllers/index.js:166:15
at /var/app/current/plugins/tn_job/services/facet_rendering_service.js:431:13
at /var/app/current/include/service/entities/template_service.js:406:13
at /var/app/current/node_modules/async/lib/async.js:254:17
at /var/app/current/node_modules/async/lib/async.js:157:25
at /var/app/current/node_modules/async/lib/async.js:251:21
at /var/app/current/node_modules/async/lib/async.js:615:34
at /var/app/current/include/service/entities/template_service.js:384:28
at /var/app/current/node_modules/async/lib/async.js:610:21
at /var/app/current/node_modules/async/lib/async.js:249:17
at iterate (/var/app/current/node_modules/async/lib/async.js:149:13)
at /var/app/current/node_modules/async/lib/async.js:160:25
at /var/app/current/node_modules/async/lib/async.js:251:21
at /var/app/current/node_modules/async/lib/async.js:615:34
at /var/app/current/include/service/entities/template_service.js:396:25
at handler (/var/app/current/include/service/entities/template_service.js:525:17)
at TemplateService.handleReplacement (/var/app/current/include/service/entities/template_service.js:540:13)
at doFlagProcessing (/var/app/current/include/service/entities/template_service.js:440:22)
at TemplateService.processFlag (/var/app/current/include/service/entities/template_service.js:474:9)
at /var/app/current/include/service/entities/template_service.js:388:26
at /var/app/current/node_modules/async/lib/async.js:610:21
at /var/app/current/node_modules/async/lib/async.js:249:17
at iterate (/var/app/current/node_modules/async/lib/async.js:149:13)
at /var/app/current/node_modules/async/lib/async.js:160:25
at /var/app/current/node_modules/async/lib/async.js:251:21
at /var/app/current/node_modules/async/lib/async.js:615:34
at /var/app/current/include/service/entities/template_service.js:396:25
at doFlagProcessing (/var/app/current/include/service/entities/template_service.js:448:17)
at TemplateService.processFlag (/var/app/current/include/service/entities/template_service.js:474:9)
at /var/app/current/include/service/entities/template_service.js:388:26
at /var/app/current/node_modules/async/lib/async.js:610:21
at /var/app/current/node_modules/async/lib/async.js:249:17
at iterate (/var/app/current/node_modules/async/lib/async.js:149:13)
at /var/app/current/node_modules/async/lib/async.js:160:25
at /var/app/current/node_modules/async/lib/async.js:251:21
at /var/app/current/node_modules/async/lib/async.js:615:34
at /var/app/current/include/service/entities/template_service.js:384:28
at /var/app/current/node_modules/async/lib/async.js:610:21
at /var/app/current/node_modules/async/lib/async.js:249:17
at iterate (/var/app/current/node_modules/async/lib/async.js:149:13)
at /var/app/current/node_modules/async/lib/async.js:160:25
at /var/app/current/node_modules/async/lib/async.js:251:21
at /var/app/current/node_modules/async/lib/async.js:615:34
at /var/app/current/include/service/entities/template_service.js:396:25
at handler (/var/app/current/include/service/entities/template_service.js:525:17)
at TemplateService.handleReplacement (/var/app/current/include/service/entities/template_service.js:540:13)
at doFlagProcessing (/var/app/current/include/service/entities/template_service.js:440:22)
at TemplateService.processFlag (/var/app/current/include/service/entities/template_service.js:474:9)
at /var/app/current/include/service/entities/template_service.js:388:26
at /var/app/current/node_modules/async/lib/async.js:610:21
at /var/app/current/node_modules/async/lib/async.js:249:17
at iterate (/var/app/current/node_modules/async/lib/async.js:149:13)
at /var/app/current/node_modules/async/lib/async.js:160:25
at /var/app/current/node_modules/async/lib/async.js:251:21
at /var/app/current/node_modules/async/lib/async.js:615:34
at /var/app/current/include/service/entities/template_service.js:384:28
at /var/app/current/node_modules/async/lib/async.js:610:21
at /var/app/current/node_modules/async/lib/async.js:249:17
at iterate (/var/app/current/node_modules/async/lib/async.js:149:13)
at async.eachSeries (/var/app/current/node_modules/async/lib/async.js:165:9)
at _asyncMap (/var/app/current/node_modules/async/lib/async.js:248:13)
at Object.mapSeries (/var/app/current/node_modules/async/lib/async.js:231:23)
at Object.async.series (/var/app/current/node_modules/async/lib/async.js:608:19)
at TemplateService.process (/var/app/current/include/service/entities/template_service.js:405:15)
at /var/app/current/include/service/entities/template_service.js:356:18
at /var/app/current/include/service/entities/template_service.js:327:21
at Object.async.whilst (/var/app/current/node_modules/async/lib/async.js:686:13)
at /var/app/current/node_modules/async/lib/async.js:682:23
at /var/app/current/include/service/entities/template_service.js:323:25
at /var/app/current/include/service/simple_layered_service.js:95:17
at Object.async.whilst (/var/app/current/node_modules/async/lib/async.js:686:13)
at /var/app/current/node_modules/async/lib/async.js:682:23
at /var/app/current/include/service/simple_layered_service.js:76:21
at callback (/var/app/current/include/service/template_entity_service.js:75:13)
at /var/app/current/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:76:16
at wrappedCallback (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:312:17)
at wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:157:28)
at wrappedCallback (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:438:66)
at wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:157:28)
at fs.js:334:14
at /var/app/current/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:42:10
at wrappedCallback (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:312:17)
at wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:157:28)
at wrappedCallback (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:438:66)
at wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:157:28)
at FSReqWrap.oncomplete (fs.js:95:15)

**Comment by brianhyder** [comment]
Hey,

For the people that are seeing the issue can you verify that their browsers are passing the language header in the expected format of ```en-US```?

We recently updated the casing of the localization files, on 0.5.0, to be named in the proper casing and format as referenced above.  On windows systems file naming is case insensitive.  And when files are renamed in Git the file system does not actually update the file because it considers the naming unchanged due to the fact it ignores case.  For those that are seeing the issue can you verify that the casing is correct for the localization files?

Aside from the main issue.  I would strongly caution against using the ```localize``` function.  I am finishing up the first phase of the localization refactor and that function will be deprecated as part of that.  It is slow and very inefficient.  I plan to finish up early next week but until then I would look at using the ```get``` method to localize individual keys.

**Comment by btidwell** [comment]
Unfortunately we don't have that kind a visibility in our access logs.  From what we can tell in our nginx and nodejs logs from elastic beanstalk it could be a result of a cloud front request.  We have our site cached on the Amazon Cloud Front CDN.  But we can't be 100% sure as the two logs we are comparing are sort of independent of each other and because of the fact that the page isn't showing any errors when served from Cloud Front.

We have a small fix/hack in our environment where we convert the result of the best function in localization.js

loc.toString().replace('_','-').toLowerCase();

When you are finished with the refactor we can remove the hack, pull in your latest changes, and update the localization call in our theme.  We can see if that error returns after we deploy.

Ben Tidwell
Software Engineer III | Talent Network
5550-A Peachtree Pkwy, Norcross GA 30092

**Comment by brianhyder** [comment]
@btidwell The localization service refactor has been completed.  Would you all mind keeping an eye out for this after the updates are pulled into your fork to see if this is still an issue?

**Comment by blakecallens** [comment]
Are we good to close this one?

**Comment by btidwell** [comment]
Hey Blake,  Yes it looks like things are good.  We've been running the latest in production for almost the past week now and I don't see any errors around localization popping up.

**Comment by blakecallens** [comment]
Thanks, @btidwell!
