### ISSUE TITLE
Cannot create articles anymore

### ISSUE THREAD

**Issue by dennisgermany** [pencilblue/pencilblue#736]
Hi,
I just updated from 0.4.0 to the latest version from master (0.4.1). 
Since then it is not possible anymore to create articles. When going to the "New Article page" I get the following error in Chrome console: 

```
Uncaught SyntaxError: Unexpected token <
^rangy_saverestore_src^:1 Uncaught SyntaxError: Unexpected token <
angular.js:9563 ReferenceError: rangy is not defined
    at link (http://localhost:8080/js/angular/directives/wysiwyg.js:370:9)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:62:364
    at J (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:52:492)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:59:302
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:70:373
    at l.promise.then.H (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:97:5)
    at l.promise.then.H (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:97:5)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:98:173
    at h.a.$get.h.$eval (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:108:40)
    at h.a.$get.h.$digest (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:105:331) <div layout="layout" media="article.article_media" class="ng-isolate-scope"> 
```

When clicking the save button I get:

```
TypeError: Cannot read property 'length' of undefined
    at h.$scope.isWysiwygValid (new:727)
    at h.$scope.saveArticle (new:765)
    at Za.functionCall (angular.js:10348)
    at angular.js:18333
    at h.a.$get.h.$eval (angular.js:12175)
    at h.a.$get.h.$apply (angular.js:12273)
    at HTMLAnchorElement.<anonymous> (angular.js:18332)
    at HTMLAnchorElement.m.event.dispatch (jquery-1.11.1.min.js:3)
    at HTMLAnchorElement.m.event.add.r.handle (jquery-1.11.1.min.js:3)
```

Thanks!

**Comment by blakecallens** [comment]
I think if you go to your library settings and reload either your CDN or Bower defaults, everything will work again. If you're using bower then also run another bower install to update.

**Comment by dennisgermany** [comment]
Hey,

going to Admin->Settings->Libraries and hitting "Use CDNs" solved the problem.
I can create articles again.

Thank you very much for your lightning fast reply.

**Comment by blakecallens** [comment]
Glad to help. For future reference, for anyone that experiences this issue, we added the rangy library for the new wysiwyg in 0.4.1, so that library needs to be updated in the settings.
