### ISSUE TITLE
Install error on Ubuntu-based systems

### ISSUE THREAD

**Issue by thiagodebastos** [pencilblue/pencilblue#782]
hey guys! I've been wanting to move away from WordPress to PencilBlue as a way to acquaint myself further with Node and Mongo. I've been trying for about a week now and the furthest I've been able to get is to have Pencilblue working last night but then this morning it just wouldn't start up again. I just tried installing pencilblue on a Digital Ocean droplet pre-packaged with the MEAN stack but got this error again:

I've also tried this on my laptop using Ubuntu 15.04, on several Vagrant boxes running 14.04 too. Some were fresh some were pre-loaded with Mongo.

From the following log, is there anything obvious that you guys can see? Or even point me in the right direction? 
Thank you!

``` bash
root@pencilblue:/srv/www/pencilblue# pbctrl install www
PencilBlue: Site Name:  (My PencilBlue Site) 
PencilBlue: Site Root:  (http://localhost:8080) 
PencilBlue: Address to bind to:  (0.0.0.0) 
PencilBlue: Site Port:  (8080) 
PencilBlue: MongoDB URL:  (mongodb://127.0.0.1:27017/) 
PencilBlue: Database Name:  (pencilblue) 
PencilBlue: Do you want to install Bower components?:  (y/N) y
Installing PencilBlue to /srv/www/pencilblue/www/...
Cloning into 'www'...
Installing Node modules...
npm WARN package.json pencilblue@0.4.1 No license field.

> kerberos@0.0.15 install /srv/www/pencilblue/www/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory `/srv/www/pencilblue/www/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
 #include <gssapi/gssapi.h>
                           ^
compilation terminated.
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
make: Leaving directory `/srv/www/pencilblue/www/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.13.0-57-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /srv/www/pencilblue/www/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 

> bson-ext@0.1.13 install /srv/www/pencilblue/www/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/srv/www/pencilblue/www/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
  SOLINK_MODULE(target) Release/obj.target/bson.node
  COPY Release/bson.node
make: Leaving directory `/srv/www/pencilblue/www/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build'
process@0.10.1 node_modules/process

mocha-lcov-reporter@0.0.1 node_modules/mocha-lcov-reporter

htmlencode@0.0.4 node_modules/htmlencode

locale@0.0.20 node_modules/locale

formidable@1.0.17 node_modules/formidable

async@0.9.0 node_modules/async

node-uuid@1.4.3 node_modules/node-uuid

redis@0.12.1 node_modules/redis

cookies@0.5.0 node_modules/cookies
└── keygrip@1.0.1

async-eventemitter@0.2.2 node_modules/async-eventemitter
└── async@0.2.10

node.extend@1.1.3 node_modules/node.extend
└── is@2.1.0

semver@4.3.3 node_modules/semver

fakeredis@0.3.0 node_modules/fakeredis

winston@0.9.0 node_modules/winston
├── cycle@1.0.3
├── stack-trace@0.0.9
├── eyes@0.1.8
├── isstream@0.1.2
├── pkginfo@0.3.0
└── colors@1.0.3

should@5.0.1 node_modules/should
├── should-type@0.0.4
├── should-equal@0.3.1
└── should-format@0.0.7

mocha@2.1.0 node_modules/mocha
├── escape-string-regexp@1.0.2
├── diff@1.0.8
├── growl@1.8.1
├── commander@2.3.0
├── debug@2.0.0 (ms@0.6.2)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)
└── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)

sanitize-html@1.1.7 node_modules/sanitize-html
├── he@0.4.1
├── htmlparser2@3.3.0 (domelementtype@1.3.0, domutils@1.1.6, domhandler@2.1.0, readable-stream@1.0.33)
└── lodash@2.4.2

nodemailer@0.5.3 node_modules/nodemailer
├── simplesmtp@0.3.35 (xoauth2@0.1.8, rai@0.1.12)
└── mailcomposer@0.2.12 (mime@1.2.11, he@0.3.6, dkim-signer@0.1.2, follow-redirects@0.0.3, mimelib@0.2.19)

coveralls@2.11.2 node_modules/coveralls
├── lcov-parse@0.0.6
├── log-driver@1.2.4
├── request@2.40.0 (forever-agent@0.5.2, aws-sign2@0.5.0, oauth-sign@0.3.0, stringstream@0.0.4, tunnel-agent@0.4.1, json-stringify-safe@5.0.1, qs@1.0.2, mime-types@1.0.2, form-data@0.1.4, tough-cookie@2.2.0, http-signature@0.10.1, hawk@1.1.1)
└── js-yaml@3.0.1 (argparse@0.1.16, esprima@1.0.4)

istanbul@0.3.6 node_modules/istanbul
├── which@1.0.9
├── abbrev@1.0.7
├── supports-color@1.2.1
├── wordwrap@0.0.3
├── nopt@3.0.4
├── once@1.3.2 (wrappy@1.0.1)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── resolve@0.7.4
├── fileset@0.1.8 (minimatch@0.4.0, glob@3.2.11)
├── esprima@2.0.0
├── escodegen@1.3.3 (estraverse@1.5.1, esutils@1.0.0, source-map@0.1.43, esprima@1.1.1)
├── handlebars@1.3.0 (optimist@0.3.7, uglify-js@2.3.6)
└── js-yaml@3.4.2 (esprima@2.2.0, argparse@1.0.2)

mongodb@2.0.33 node_modules/mongodb
├── readable-stream@1.0.31 (isarray@0.0.1, inherits@2.0.1, string_decoder@0.10.31, core-util-is@1.0.1)
└── mongodb-core@1.1.32 (kerberos@0.0.15, bson@0.3.2)

npm@2.10.1 node_modules/npm
Retrieving Bower components...
bower ESUDO         Cannot be run with sudo

Additional error details:
Since bower is a user command, there is no need to execute it with superuser permissions.
If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.

http://www.joyent.com/blog/installing-node-and-npm
https://gist.github.com/isaacs/579814

You can however run a command with sudo using --allow-root option
Creating config.js...
```

UPDATE: I am currently trying this fix: https://github.com/rvagg/node-libssh/issues/48
UPDATE 2: The above fix didn't work.

**Comment by brianhyder** [comment]
I think it is trying to execute bower with sudo permissions which it shouldn't have or need.  The virtual boxes and containers don't allow sudo commands.  If you followed the README it says to use sudo which should not be needed.  

One of two options will most likely get you up and moving:

1.  Uninstall the pencilblue-cli and re-install it without the sudo command.  Then try running the installer again.  

2. Manually install PB:
2.1 Ensure node, npm, bower, and git are installed
2.2 git clone https://github.com/pencilblue/pencilblue.git
2.3 cd pencilblue
2.4 npm install
2.5 bower install
2.6 Create a config.js from ./sample.config.js
2.7 node pencilblue.js

Let us know if you have any other issues.  We'll help you get through them.
