### ISSUE TITLE
Apply Settings

### ISSUE THREAD

**Issue by amirsaber** [pencilblue/pencilblue#803]
In site settings page of admin panel, if I change the option of help to improve pencilblue and then click on apply change button, it will spin forever, but if I refresh it I can see the setting took place.

###browser

https://localhost/actions/admin/site_settings 500 (Internal Server Error)

TypeError: Cannot read property 'length' of null
    at ConfigurationSettingsPostController.BaseControllerModule.BaseController.hasRequiredParams (/app/controllers/base_controller.js:352:56)
    at /app/plugins/pencilblue/controllers/actions/admin/site_settings/configuration.js:33:32
    at /app/controllers/base_controller.js:306:13
    at IncomingMessage. (/app/controllers/base_controller.js:335:13)
    at emitNone (events.js:67:13)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:450:9)
    at process._tickDomainCallback (node.js:405:17)

###server

2015-11-05T20:47:32.245Z - error: [4] RequestHandler: An error occurred during controller execution. URL=[POST:/actions/admin/site_settings] ROUTE={"path":"actions/admin/site_settings","pattern":"^/actions/admin/site_settings[/]{0,1}$","path_vars":{},"expression":{},"themes":{"pencilblue":{"POST":{"method":"POST","path":"/actions/admin/site_settings","access_level":4,"auth_required":true,"content_type":"text/html"}}}}
TypeError: Cannot read property 'length' of null
    at ConfigurationSettingsPostController.BaseControllerModule.BaseController.hasRequiredParams (/home/ubuntu/workspace/pencilblue/controllers/base_controller.js:352:56)
    at /home/ubuntu/workspace/pencilblue/plugins/pencilblue/controllers/actions/admin/site_settings/configuration.js:33:32
    at /home/ubuntu/workspace/pencilblue/controllers/base_controller.js:306:13
    at IncomingMessage.<anonymous> (/home/ubuntu/workspace/pencilblue/controllers/base_controller.js:335:13)
    at emitNone (events.js:67:13)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickDomainCallback (node.js:384:17)

**Comment by amirsaber** [comment]
I've noticed these so far, when call_home variable has been set to false, $scope.config load it as null by default and that cause a problem in function getJSONPostParams(configuration.js line 32). Then in line 42 calling settings.set returns data as empty and util.isError function sees it as an error and call the cb with that. I also noticed that in line 46 of configuration.js file in content of cb result has been used while it should be data.
