### ISSUE TITLE
[0.5.0] Navigating to an unregistered site causes process failure

### ISSUE THREAD

**Issue by brianhyder** [pencilblue/pencilblue#891]
With multi-site enabled:
Navigate to an unregistered site.  An uncaught failure occurs resulting in the process shutting down.

```
2015-12-08T21:26:22.097Z - error: [M]  Error: The host (test2.localhost:8080) has not been registered with a site. In single site mode, you must use your site root (http://localhost:8080).
    at RequestHandlerModule.RequestHandler.onSessionRetrieved (/Users/brian/code/pencilblue/include/http/request_handler.js:700:31)
    at /Users/brian/code/pencilblue/include/http/request_handler.js:498:18
    at SessionHandler.SessionModule.SessionHandler.open (/Users/brian/code/pencilblue/include/session/session.js:121:13)
    at RequestHandlerModule.RequestHandler.handleRequest (/Users/brian/code/pencilblue/include/http/request_handler.js:480:20)
    at PencilBlue.onHttpConnect (/Users/brian/code/pencilblue/pencilblue.js:298:17)
    at Server.<anonymous> (/Users/brian/code/pencilblue/pencilblue.js:246:26)
    at emitTwo (events.js:87:13)
    at Server.emit (events.js:172:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:507:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
2015-12-08T21:26:22.098Z - error: [M] System[M]: uncaught Exception detected :  TypeError: Cannot read property 'uid' of undefined
    at getActiveTheme (/Users/brian/code/pencilblue/include/http/request_handler.js:640:144)
    at RequestHandlerModule.RequestHandler.serveError (/Users/brian/code/pencilblue/include/http/request_handler.js:647:9)
    at RequestHandlerModule.RequestHandler.onSessionRetrieved (/Users/brian/code/pencilblue/include/http/request_handler.js:702:18)
    at /Users/brian/code/pencilblue/include/http/request_handler.js:498:18
    at SessionHandler.SessionModule.SessionHandler.open (/Users/brian/code/pencilblue/include/session/session.js:121:13)
    at RequestHandlerModule.RequestHandler.handleRequest (/Users/brian/code/pencilblue/include/http/request_handler.js:480:20)
    at PencilBlue.onHttpConnect (/Users/brian/code/pencilblue/pencilblue.js:298:17)
    at Server.<anonymous> (/Users/brian/code/pencilblue/pencilblue.js:246:26)
    at emitTwo (events.js:87:13)
    at Server.emit (events.js:172:7)
```

The new error handlers for HTML MIME types hand off to a controller.  The base controller expects a site object to be available.  The fix here is to ensure that when a site is not available the global context is passed.

**Comment by cchatham** [comment]
@btidwell @andparker didn't we fix this at one point?

**Comment by brianhyder** [comment]
Yes, this is totally on me.  I'm about to submit a fix.
