### ISSUE TITLE
A Util.inherits test doesn't work

### ISSUE THREAD

**Issue by bargenson** [pencilblue/pencilblue#963]
Hi,

When I run `npm test` on a new PencilBlue project (v0.5.0), I get the following test failure:

```
Util.inherits
      ✓ should throw an error when null is passed for the first type 
      ✓ should throw an error when null is passed for the second type 
      1) should cause Type2 to inherit the prototype function and static functions/properties of type 1


  356 passing (3s)
  1 failing

  1) Util Util.inherits should cause Type2 to inherit the prototype function and static functions/properties of type 1:

      AssertionError: expected [Function] to equal [Function] (, A has 'function (){var j = 8;}' and B has 'function (){var y = 1;}')
      + expected - actual

      
      at Assertion.fail (/Users/bargenson/tmp/vengo-assistance/node_modules/should/lib/assertion.js:196:17)
      at Assertion.prop.(anonymous function) [as eql] (/Users/bargenson/tmp/vengo-assistance/node_modules/should/lib/assertion.js:81:17)
      at Context.<anonymous> (/Users/bargenson/tmp/vengo-assistance/test/include/util_tests.js:999:49)
      at callFn (/Users/bargenson/tmp/vengo-assistance/node_modules/mocha/lib/runnable.js:251:21)
      at Test.Runnable.run (/Users/bargenson/tmp/vengo-assistance/node_modules/mocha/lib/runnable.js:244:7)
      at Runner.runTest (/Users/bargenson/tmp/vengo-assistance/node_modules/mocha/lib/runner.js:374:10)
      at /Users/bargenson/tmp/vengo-assistance/node_modules/mocha/lib/runner.js:452:12
      at next (/Users/bargenson/tmp/vengo-assistance/node_modules/mocha/lib/runner.js:299:14)
      at /Users/bargenson/tmp/vengo-assistance/node_modules/mocha/lib/runner.js:309:7
      at next (/Users/bargenson/tmp/vengo-assistance/node_modules/mocha/lib/runner.js:248:23)
      at Immediate._onImmediate (/Users/bargenson/tmp/vengo-assistance/node_modules/mocha/lib/runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:383:17)
```

Is that a PencilBlue issue or an environment issue?

Thanks!

**Comment by brianhyder** [comment]
Please see our README or package.json file.  We currently do not support Node v5.x
