### ISSUE TITLE
Error when installing a plugin which has a dependency that contains a dot in its name

### ISSUE THREAD

**Issue by JahlomP** [pencilblue/pencilblue#974]
Getting the following error while installing a plugin which has a dependency that contains a dot in its name
```js
2016-03-23T01:24:41.555Z:[9] INSTALL_PLUGIN_osen: Error: key socket.io must not contain '.'
    at Error (native)
    at serializeInto (D:\Social\Projects\Preterk\Pencilblue\pencilblue\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\lib\bson\parser\serializer.js:682:19)
    at serializeObject (D:\Social\Projects\Preterk\Pencilblue\pencilblue\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\lib\bson\parser\serializer.js:280:18)
    at serializeInto (D:\Social\Projects\Preterk\Pencilblue\pencilblue\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\lib\bson\parser\serializer.js:705:17)
    at serializeObject (D:\Social\Projects\Preterk\Pencilblue\pencilblue\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\lib\bson\parser\serializer.js:280:18)
    at serializeInto (D:\Social\Projects\Preterk\Pencilblue\pencilblue\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\lib\bson\parser\serializer.js:551:17)
    at serializeObject (D:\Social\Projects\Preterk\Pencilblue\pencilblue\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\lib\bson\parser\serializer.js:280:18)
    at serializeInto (D:\Social\Projects\Preterk\Pencilblue\pencilblue\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\lib\bson\parser\serializer.js:705:17)
    at serialize (D:\Social\Projects\Preterk\Pencilblue\pencilblue\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\lib\bson\bson.js:47:27)
    at Query.toBin (D:\Social\Projects\Preterk\Pencilblue\pencilblue\node_modules\mongodb\node_modules\mongodb-core\lib\connection\commands.js:122:25)

**Comment by brianhyder** [comment]
@JahlomP What version of the mongo driver are you using?

**Comment by brianhyder** [comment]
I'll try to replicate.  Looks like there might be a workaround: http://stackoverflow.com/questions/12397118/mongodb-dot-in-key-name

**Comment by JahlomP** [comment]
K

**Comment by JahlomP** [comment]
Should we go for the replacement with Unicodes?

**Comment by brianhyder** [comment]
I'm going to look to see if we can pass the option to ignore the key check.  If not then we'll have to investigate a bit further.  I'm not sure how changing the characters to unicode would affect the calls to NPM.

**Comment by JahlomP** [comment]
K
