### ISSUE TITLE
Crash opening article admin view as writer

### ISSUE THREAD

**Issue by dennisgermany** [pencilblue/pencilblue#980]
Hi,

I'm getting the following error when opening the article admin view with role WRITER. (The other roles seem to work fine.)

ReferenceError: where is not defined
    at ManageArticles.render (/Users/dennis/Development/git/pencilblue/plugins/pencilblue/controllers/admin/content/articles/manage_articles.js:36:13)
    at /Users/dennis/Development/git/pencilblue/include/http/request_handler.js:1148:79
    at process._tickDomainCallback (node.js:381:11)

I just tried it again with the current master 0.5.1 and the error is still there.

Thanks!
--Dennis

**Comment by brianhyder** [comment]
Confirmed as a bug.  The bug was introduced when the controller was switched over to retrieve the data via the API and not render as part of the page.  The original behavior was for the view to only render the articles created by the writer.  This is probably not intended behavior.  A writer should be able to view all articles but should not be able to edit all articles.

The fix should ensure:
* the article service validation checks the permission levels
* the article API allows for filtering by author

**Comment by brianhyder** [comment]
UPDATE: The ability to filter articles by author will be addressed in #1006

**Comment by ceballos59** [comment]
I have a cuestion ? - In current version Penciblue writers can not yet manage articles ?

**Comment by brianhyder** [comment]
We are planning to correct this as part of the 1.0 release.  We are happy to entertain PRs to fix it in the meantime
