### ISSUE TITLE
Can't get Pencilblue to work in an automated (docker) setup

### ISSUE THREAD

**Issue by vpetersson** [pencilblue/pencilblue#992]
I'm trying to get Pencilblue to work in a dockerized environment. The code is available on [Github](https://github.com/vpetersson/docker-pencilblue) and it is also automatically built on [Docker Hub](https://hub.docker.com/r/vpetersson/pencilblue/). 

The goal is to make the setup easier. In the current iteration, I've hardcoded the setup to use a MongoDB replica set with hard coded values, but this could be parameterized later.

You can reproduce this using something like:
```
$ docker run -d -p 80:8080 --name pb  vpetersson/pencilblue
```

The system will start up just fine, but as soon as you access the site, you get the following error:

```
Override file [/opt/pb/config.js] will be applied.
2016-03-31T13:57:29.884Z - info: [M] SystemStartup: Log Level is: info
2016-03-31T13:57:30.899Z - info: [M] System[M]: 1 workers spawned. Listening for disconnects.
Override file [/opt/pb/config.js] will be applied.
2016-03-31T13:57:31.677Z - info: [1] SystemStartup: Log Level is: info
2016-03-31T13:57:33.715Z - info: [1] PencilBlue: Ensuring indices...
2016-03-31T13:57:34.301Z - info: [1] ServerInitializer: HTTP server starting, binding on IP 0.0.0.0 and port: 8080
2016-03-31T13:57:34.316Z - info: [1] PencilBlue: Ready to run!
2016-03-31T13:57:46.406Z - error: [1]  Error: The host (192.168.33.10) has not been registered with a site. In single site mode, you must use your site root (http://127.0.0.1:8080).
    at RequestHandlerModule.RequestHandler.onSessionRetrieved (/opt/pb/include/http/request_handler.js:780:23)
    at /opt/pb/include/http/request_handler.js:554:18
    at SessionHandler.SessionModule.SessionHandler.open (/opt/pb/include/session/session.js:121:13)
    at RequestHandlerModule.RequestHandler.handleRequest (/opt/pb/include/http/request_handler.js:539:20)
    at PencilBlue.onHttpConnect (/opt/pb/pencilblue.js:264:17)
    at Server.context.onRequest (/opt/pb/pencilblue.js:217:22)
    at emitTwo (events.js:100:13)
    at Server.emit (events.js:185:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:537:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
2016-03-31T13:57:46.454Z - error: [1] System[1]: uncaught Exception detected : TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.join (path.js:1251:7)
    at ErrorFormatters.html (/opt/pb/include/error/formatters/error_formatters.js:130:18)
    at Function.ErrorFormatters.formatForMime (/opt/pb/include/error/formatters/error_formatters.js:292:9)
    at /opt/pb/include/http/request_handler.js:730:32
    at /opt/pb/include/http/request_handler.js:711:17
    at /opt/pb/include/service/simple_layered_service.js:94:17
    at Object.async.whilst (/opt/pb/node_modules/async/lib/async.js:686:13)
    at /opt/pb/node_modules/async/lib/async.js:682:23
    at /opt/pb/include/service/simple_layered_service.js:75:21
/opt/pb/node_modules/fakeredis/main.js:47
      throw new Error("fakeredis: You've closed this connection with .end(), cannot " + command);
      ^

Error: fakeredis: You've closed this connection with .end(), cannot quit
    at RedisClient.cl.send_command (/opt/pb/node_modules/fakeredis/main.js:47:13)
    at RedisClient.(anonymous function) (/opt/pb/node_modules/redis/index.js:991:25)
    at Object.CacheModule.CacheFactory.shutdown [as CacheFactory] (/opt/pb/include/dao/cache.js:87:20)
    at Domain.<anonymous> (/opt/pb/include/system/system.js:227:44)
    at Domain.run (domain.js:228:14)
    at /opt/pb/include/system/system.js:225:19
    at /opt/pb/node_modules/async/lib/async.js:570:21
    at /opt/pb/node_modules/async/lib/async.js:249:17
    at /opt/pb/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
Override file [/opt/pb/config.js] will be applied.
2016-03-31T13:57:47.687Z - info: [2] SystemStartup: Log Level is: info
2016-03-31T13:57:49.637Z - info: [2] PencilBlue: Ensuring indices...
2016-03-31T13:57:50.125Z - info: [2] ServerInitializer: HTTP server starting, binding on IP 0.0.0.0 and port: 8080
2016-03-31T13:57:50.137Z - info: [2] PencilBlue: Ready to run!
```

Any clues on why that is?

**Comment by blakecallens** [comment]
Looks like your config.js file isn't configured to your docker instance.

**Comment by vpetersson** [comment]
I don't think that is it. [This](https://github.com/vpetersson/docker-pencilblue/blob/master/Dockerfile#L20) line copies in the `config.js` into the correct location.

**Comment by brianhyder** [comment]
The issue seems to be that the config file is not setting the x_forwarded_for parameter to true.  This will allow the incoming request to match the registered site, in single site mode, which would be your site root in your config file.  This sounds very similar to the issues users were seeing with Cloud 9 in #1005 which we were able to solve.  Please check out that answer and let us know if that does not resolve the issue.

**Comment by vpetersson** [comment]
Thanks. Will investigate this and try it out later in the week.

**Comment by Jehu** [comment]
any news here?

**Comment by vpetersson** [comment]
I haven't had a chance to look at this in recent time as I had to shift priorities over to other things.
